### ISSUE TITLE
Error on Compiling 

### ISSUE THREAD

**Issue by aakashsengar** [Alone2/capacitor-notificationlistener#5] opened 2021-06-19 05:12 UTC
![Screenshot 2021-06-19 at 10 41 20 AM](https://user-images.githubusercontent.com/11537219/122631692-fb2eb900-d0ea-11eb-8ec7-f2d9ca42d2e0.png)

**Comment by Alone2** [comment] 2021-06-20 07:50
I was unable to reproduce your error message, but it's quite likely that the error is because you use capacitor v3 and this plugin was designed for v2.

If that's not the case, can you provide further information about your setup and on how you got that error? Did you register the plugin correctly using  ```add(NotificationListenerPlugin.class)``` in your ```MainActivity.java```?

I will update this plugin to the newest version of capacitor sometime in the future.
Let me know if I was able to help you :smile:

**Comment by aakashsengar** [comment] 2021-06-20 08:23
Yes it's Capacitor 3, can you help me to Migrate it to Capacitor 3 my app depends on it.

**Comment by Alone2** [comment] 2021-06-20 21:36
Hey, I updated the plugin to v3 of capacitor but haven't tested it enough yet. 
You can already use it if you want to ([link](https://github.com/Alone2/capacitor-notificationlistener/tree/capV3)).
It can't be installed using npm at the minute, unfortunately. You'd have to clone the branch and import it manually (```npm install ../path/to/capacitor-notificationlistener```)

**Comment by aakashsengar** [comment] 2021-06-20 22:10
I will try. I am using ionic. My main goal is to send any notification coming to the mobile phone to BLE device. Unfortunately I am not able to do it in ionic. I have created the app with Cordova since this plugin was not working.with Cordova it works when app is running in background but stops when app is closed. Do you know if I can implement this with your plugin?

**Comment by aakashsengar** [comment] 2021-06-20 22:42
![Screenshot 2021-06-21 at 4 12 00 AM](https://user-images.githubusercontent.com/11537219/122690379-d7808580-d246-11eb-8eb7-74d7543cfb84.png)

I did the npm install still this error is coming

**Comment by Alone2** [comment] 2021-06-20 22:43
I originally didn't plan to let the plugin in the background, as I believed it was a smarter idea for it to be out of scope and thus letting the user decide which method of "running in the background" they want to use or implement themselves.

I think it be achieved through [this plugin](https://github.com/flytesoft-software/capacitor-persistent-notification) (don't know if this is working for capacitor v3) as already answered [here](https://github.com/Alone2/capacitor-notificationlistener/issues/3). To my knowledge there is no way of listening permanently to notifications in the background without a pesky, ugly notification by the app itself. I thought there was a cordova plugin somewhere which could run in the background exactly like that, but I cant find it anymore.

As you are the second person to ask for this feature, I may implement it in the future or create a new plugin that can run in the background :smile:

**Comment by Alone2** [comment] 2021-06-20 22:46
> I did the npm install still this error is coming

Try ```import { SystemNotification, SystemNotificationListener } from 'capacitor-notificationlistener';``` instead of ```import { } from 'capacitor-notificationlistener';``` and make sure you typed ```npx cap sync``` after installing. 

Maybe you need to restart your IDE - was the same for me. Suddenly the error message was gone.

**Comment by aakashsengar** [comment] 2021-06-20 22:50
![Screenshot 2021-06-21 at 4 19 21 AM](https://user-images.githubusercontent.com/11537219/122690560-dd2a9b00-d247-11eb-9757-b8779786316a.png)
Same error I am using Ionic So  `npx cap sync` to run this. first It builds the app and this error is not letting me build.
BTW I did IDE restart

**Comment by Alone2** [comment] 2021-06-20 23:15
I'm sorry, somehow I completely forgot that you need to build the plugin first. 
Apologies, that's my fault. I even had the exact same error myself, that's embarrassing...
Go to the folder where you saved ```capacitor-notificationlistener``` and run ```npm run build```. 
Then install the plugin again like you already did the last time and run ```npx cap sync``` again and so on.

Make sure in the file ```package.json``` that there is no version number but a path after ```capacitor-notificationlistener```. If that's not the case something went wrong in the installation proccess.

I need to go now and can't answer for the rest of the day. [Here's](https://github.com/Alone2/testNotificationListener) a "test" project with capacitor 3 that's working for me if you need it (the path of ```capacitor-notificationlistener``` in ```package.json``` is of course adapted to my computer, you'd need to change it to yours if you'd run it).

**Comment by aakashsengar** [comment] 2021-06-20 23:58
Thanks It worked. Unfortunately no way to keep it running in Background I think I should try React Native.
EDIT: -
Notification Listner as background Services working in React Native. even on closing the App.

**Closed as completed** 2021-06-21 07:08 UTC
Labels: enhancement
